### ISSUE TITLE
死循环栈内存溢出

### ISSUE THREAD

**Issue by ppgod15** [ZhangYuanSheng1217/RestfulTool#106]
**Describe the bug**
是不是接口出现了循环引用，导致死循环栈内存溢出了

**To Reproduce**java.lang.StackOverflowError
	at java.base/java.lang.invoke.VarHandleObjects$Array.getVolatile(VarHandleObjects.java:438)
	at java.base/java.lang.invoke.VarHandleGuards.guard_LI_L(VarHandleGuards.java:646)
	at java.base/java.util.concurrent.atomic.AtomicReferenceArray.get(AtomicReferenceArray.java:100)
	at com.intellij.psi.stubs.LazyStubList.getCachedStub(LazyStubList.java:73)
	at com.intellij.psi.stubs.LazyStubList.get(LazyStubList.java:55)
	at com.intellij.psi.stubs.LazyStubList.get(LazyStubList.java:18)
	at java.base/java.util.AbstractList$SubList.get(AbstractList.java:786)
	at com.intellij.psi.stubs.StubBase.fillFilteredChildren(StubBase.java:129)
	at com.intellij.psi.stubs.StubBase.getChildrenByType(StubBase.java:98)
	at com.intellij.psi.impl.compiled.ClsModifierListImpl.getAnnotations(ClsModifierListImpl.java:61)
	at com.intellij.psi.impl.PsiImplUtil.findAnnotation(PsiImplUtil.java:288)
	at com.intellij.psi.impl.compiled.ClsModifierListImpl.findAnnotation(ClsModifierListImpl.java:71)
	at com.intellij.psi.PsiJvmConversionHelper.getListAnnotation(PsiJvmConversionHelper.java:53)
	at com.intellij.psi.PsiModifierListOwner.getAnnotation(PsiModifierListOwner.java:41)
	at com.intellij.psi.PsiJvmModifiersOwner.getAnnotation(PsiJvmModifiersOwner.java:27)
	at com.github.restful.tool.utils.RestUtil.getQualifiedAnnotation(RestUtil.java:258)
	at com.github.restful.tool.utils.RestUtil.getQualifiedAnnotation(RestUtil.java:263)
	at com.github.restful.tool.utils.RestUtil.getQualifiedAnnotation(RestUtil.java:263)
	at com.github.restful.tool.utils.RestUtil.getQualifiedAnnotation(RestUtil.java:263)
	at com.github.restful.tool.utils.RestUtil.getQualifiedAnnotation(RestUtil.java:263)
	at com.github.restful.tool.utils.RestUtil.getQualifiedAnnotation(RestUtil.java:263)
	at com.github.restful.tool.utils.RestUtil.getQualifiedAnnotation(RestUtil.java:263)
	at com.github.restful.tool.utils.RestUtil.getQualifiedAnnotation(RestUtil.java:263)
	at com.github.restful.tool.utils.RestUtil.getQualifiedAnnotation(RestUtil.java:263)
	at com.github.restful.tool.utils.RestUtil.getQualifiedAnnotation(RestUtil.java:263)
	at com.github.restful.tool.utils.RestUtil.getQualifiedAnnotation(RestUtil.java:263)
	at com.github.restful.tool.utils.RestUtil.getQualifiedAnnotation(RestUtil.java:263)
	at com.github.restful.tool.utils.RestUtil.getQualifiedAnnotation(RestUtil.java:263)

**Comment by ppgod15** [comment]
找到原因了，controller层有方法加了一个注解@VisibleForTesting
