### ISSUE TITLE
JavaClassValidateUtil.java:304有一个空指针

### ISSUE THREAD

**Issue by zhuzhuppx** [ZhangYuanSheng1217/RestfulTool#108]
java.lang.NullPointerException: Cannot invoke "String.hashCode()" because "<local1>" is null
	at com.power.doc.utils.JavaClassValidateUtil.isFile(JavaClassValidateUtil.java:304)
	at com.power.doc.helper.ParamsBuildHelper.buildParams(ParamsBuildHelper.java:287)
	at com.power.doc.template.IBaseDocBuildTemplate.buildReturnApiParams(IBaseDocBuildTemplate.java:129)
	at com.power.doc.template.IRestDocTemplate.buildEntryPointMethod(IRestDocTemplate.java:444)
	at com.power.doc.template.IRestDocTemplate.processApiData(IRestDocTemplate.java:66)
	at com.power.doc.template.SpringBootDocBuildTemplate.getApiData(SpringBootDocBuildTemplate.java:54)
	at com.power.doc.builder.DocBuilderTemplate.listOfApiData(DocBuilderTemplate.java:391)
	at com.power.doc.builder.DocBuilderTemplate.getApiData(DocBuilderTemplate.java:75)
	at com.power.doc.builder.ApiDataBuilder.getApiData(ApiDataBuilder.java:61)
	at com.power.doc.builder.ApiDataBuilder.getApiData(ApiDataBuilder.java:43)

**Comment by zhuzhuppx** [comment]
提错地方了
