### ISSUE TITLE
IntelliJ IDEA 2024.3 (Ultimate Edition) NoSuchMethodError Exception

### ISSUE THREAD

**Issue by livem** [ZhangYuanSheng1217/RestfulTool#115]
**Describe the bug**

**Exception** here

```java
java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.idea.stubindex.KotlinAnnotationsIndex org.jetbrains.kotlin.idea.stubindex.KotlinAnnotationsIndex.getInstance()'
	at com.github.restful.tool.utils.scanner.KotlinUtil.findKtAnnotationEntryByName(KotlinUtil.java:257)
	at com.github.restful.tool.utils.scanner.KotlinUtil.findKtClassByAnnotationName(KotlinUtil.java:240)
	at com.github.restful.tool.utils.scanner.KotlinUtil.getRestfulKotlinClasses(KotlinUtil.java:216)
	at com.github.restful.tool.utils.scanner.KotlinUtil.getKotlinRequests(KotlinUtil.java:51)
	at com.github.restful.tool.utils.scanner.framework.Spring.getService(Spring.java:82)
	at com.github.restful.tool.utils.ApiServices.getModuleApis(ApiServices.java:115)
	at com.github.restful.tool.utils.ApiServices.getApis(ApiServices.java:75)
	at com.github.restful.tool.view.window.frame.Window.getRequests(Window.java:241)
	at com.github.restful.tool.view.window.frame.Window.lambda$new$0(Window.java:111)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor.callWrapped(NonBlockingReadActionImpl.java:857)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor$MonitoredComputation.call(NonBlockingReadActionImpl.java:889)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:618)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$4(NonBlockingReadActionImpl.java:581)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:351)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:971)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:95)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:157)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:140)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:223)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:674)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:749)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:673)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:203)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:137)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:95)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:581)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:480)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$2(NonBlockingReadActionImpl.java:495)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Expected behavior**
Spring Boot Project does not render all RESTful APIs.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - IntelliJ IDEA 2024.3 (Ultimate Edition) Build #IU-243.21565.193
 - RestfulTool Version: 1.4.5

**Comment by future0923** [comment]
我自己开发了个，支持了最新版本的idea。https://debug-tools.cc/zh/guide/search-http.html
