### ISSUE TITLE
IntelliJ IDEA 2024.3.1 (Ultimate Edition) 版本无法使用

### ISSUE THREAD

**Issue by jon-jian** [ZhangYuanSheng1217/RestfulTool#116]
**Describe the bug**
IntelliJ IDEA 2024.3.1 (Ultimate Edition) 版本 restfulTool插件报错，报错如下：

**Comment by jon-jian** [comment]
java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.idea.stubindex.KotlinAnnotationsIndex org.jetbrains.kotlin.idea.stubindex.KotlinAnnotationsIndex.getInstance()'
	at com.github.restful.tool.utils.scanner.KotlinUtil.findKtAnnotationEntryByName(KotlinUtil.java:257)
	at com.github.restful.tool.utils.scanner.KotlinUtil.findKtClassByAnnotationName(KotlinUtil.java:240)
	at com.github.restful.tool.utils.scanner.KotlinUtil.getRestfulKotlinClasses(KotlinUtil.java:216)
	at com.github.restful.tool.utils.scanner.KotlinUtil.getKotlinRequests(KotlinUtil.java:51)
	at com.github.restful.tool.utils.scanner.framework.Spring.getService(Spring.java:82)
	at com.github.restful.tool.utils.ApiServices.getModuleApis(ApiServices.java:115)
	at com.github.restful.tool.utils.ApiServices.getApis(ApiServices.java:75)
	at com.github.restful.tool.view.window.frame.Window.getRequests(Window.java:241)
	at com.github.restful.tool.view.window.frame.Window.lambda$new$0(Window.java:111)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor.callWrapped(NonBlockingReadActionImpl.java:857)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor$MonitoredComputation.call(NonBlockingReadActionImpl.java:889)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:618)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$4(NonBlockingReadActionImpl.java:581)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:351)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:971)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:95)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:157)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:140)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:223)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:674)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:749)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:673)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:203)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:137)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:95)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:581)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:480)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$2(NonBlockingReadActionImpl.java:495)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by future0923** [comment]
我自己开发了个，支持了最新版本的idea。https://debug-tools.cc/zh/guide/search-http.html

**Comment by jon-jian** [comment]
> 我自己开发了个，支持了最新版本的idea。https://debug-tools.cc/zh/guide/search-http.html

老哥，地址404了，可以发个新的吗？

**Comment by future0923** [comment]
> https://debug-tools.cc/zh/guide/search-http.html

https://debug-tools.cc/guide/search-http.html，中文改成默认语言了，还可以尝试下我的其他功能，主要是热部署、热重载、调用java方法等

**Comment by future0923** [comment]
> > 我自己开发了个，支持了最新版本的idea。https://debug-tools.cc/zh/guide/search-http.html
> 
> 老哥，地址404了，可以发个新的吗？

[https://debug-tools.cc/guide/search-http.html](https://debug-tools.cc/guide/search-http.html)，中文改成默认语言了，还可以尝试下我的其他功能，主要是热部署、热重载、调用java方法等

**Comment by jon-jian** [comment]
> > > 我自己开发了个，支持了最新版本的idea。https://debug-tools.cc/zh/guide/search-http.html
> > 
> > 
> > 老哥，地址404了，可以发个新的吗？
> 
> https://debug-tools.cc/guide/search-http.html，中文改成默认语言了，还可以尝试下我的其他功能，主要是热部署、热重载、调用java方法等

好的，感谢大佬，我试试大佬的热重载功能，嘻嘻
