### ISSUE TITLE
IDEA加载插件时抛了个空异常

### ISSUE THREAD

**Issue by mfd2033** [ZhangYuanSheng1217/RestfulTool#22]
第一个
```java
java.lang.NullPointerException
	at com.zhaow.restful.common.PsiAnnotationHelper.getAnnotationAttributeValues(PsiAnnotationHelper.java:54)
	at com.zhaow.restful.common.spring.RequestMappingAnnotationHelper.getRequestMappings(RequestMappingAnnotationHelper.java:96)
	at com.zhaow.restful.common.spring.RequestMappingAnnotationHelper.getRequestPaths(RequestMappingAnnotationHelper.java:144)
	at com.zhaow.restful.common.resolver.SpringResolver.getServiceItemList(SpringResolver.java:181)
	at com.zhaow.restful.common.resolver.SpringResolver.getRestServiceItemList(SpringResolver.java:137)
	at com.zhaow.restful.common.resolver.BaseServiceResolver.findAllSupportedServiceItemsInProject(BaseServiceResolver.java:67)
	at com.zhaow.restful.common.ServiceHelper.buildRestServiceItemListUsingResolver(ServiceHelper.java:70)
	at com.zhaow.restful.navigation.action.GotoRequestMappingContributor.getNames(GotoRequestMappingContributor.java:33)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.processContributorNames(ContributorsBasedGotoByModel.java:127)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:86)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:80)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:28)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:821)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:69)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:28)
	at com.intellij.concurrency.JobLauncherImpl.lambda$null$2(JobLauncherImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$3(JobLauncherImpl.java:111)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:791)
	at com.intellij.concurrency.JobLauncherImpl.processImmediatelyIfTooFew(JobLauncherImpl.java:122)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:41)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:45)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.processNames(ContributorsBasedGotoByModel.java:102)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.getAllNames(DefaultChooseByNameItemProvider.java:186)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.getSortedNames(DefaultChooseByNameItemProvider.java:155)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.getSortedNamesForAllWildcards(DefaultChooseByNameItemProvider.java:130)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.filterElements(DefaultChooseByNameItemProvider.java:113)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.lambda$filterElementsWithWeights$3(DefaultChooseByNameItemProvider.java:75)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.filterElementsWithWeights(DefaultChooseByNameItemProvider.java:74)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.filterElements(DefaultChooseByNameItemProvider.java:48)
	at com.zhaow.restful.navigation.action.GotoRequestMappingProvider.filterElements(GotoRequestMappingProvider.java:40)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.addElementsByPattern(ChooseByNameBase.java:1423)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.fillWithScopeExpansion(ChooseByNameBase.java:1400)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.populateElements(ChooseByNameBase.java:1383)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.performInReadAction(ChooseByNameBase.java:1346)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.lambda$runBackgroundProcess$0(ChooseByNameBase.java:1335)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$0(DumbService.java:106)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:825)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:69)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:144)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:106)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.runBackgroundProcess(ChooseByNameBase.java:1335)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$4(ProgressIndicatorUtils.java:232)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$3(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:230)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$100(ProgressIndicatorUtils.java:36)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:181)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```
第二个
```java
java.lang.NullPointerException
	at com.zhaow.restful.common.PsiAnnotationHelper.getAnnotationAttributeValues(PsiAnnotationHelper.java:54)
	at com.zhaow.restful.common.spring.RequestMappingAnnotationHelper.getRequestMappings(RequestMappingAnnotationHelper.java:96)
	at com.zhaow.restful.common.spring.RequestMappingAnnotationHelper.getRequestPaths(RequestMappingAnnotationHelper.java:144)
	at com.zhaow.restful.common.resolver.SpringResolver.getServiceItemList(SpringResolver.java:181)
	at com.zhaow.restful.common.resolver.SpringResolver.getRestServiceItemList(SpringResolver.java:137)
	at com.zhaow.restful.common.resolver.BaseServiceResolver.findAllSupportedServiceItemsInModule(BaseServiceResolver.java:38)
	at com.zhaow.restful.common.ServiceHelper.buildRestServiceItemListUsingResolver(ServiceHelper.java:55)
	at com.zhaow.restful.common.ServiceHelper.buildRestServiceProjectListUsingResolver(ServiceHelper.java:36)
	at com.zhaow.restful.navigator.RestServiceProjectsManager.lambda$getServiceProjects$0(RestServiceProjectsManager.java:68)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$0(DumbService.java:106)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:138)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:106)
	at com.zhaow.restful.navigator.RestServiceProjectsManager.getServiceProjects(RestServiceProjectsManager.java:68)
	at com.zhaow.restful.navigator.RestServiceStructure.update(RestServiceStructure.java:99)
	at com.zhaow.restful.navigator.RestServicesNavigator.lambda$scheduleStructureUpdate$1(RestServicesNavigator.java:157)
	at com.zhaow.restful.navigator.RestServicesNavigator.lambda$scheduleStructureRequest$2(RestServicesNavigator.java:174)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$smartInvokeLater$7(DumbServiceImpl.java:460)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by ZhangYuanSheng1217** [comment]
建议看看Readme.md，本插件名叫RestfulTool
