### ISSUE TITLE
spring mvc项目没有识别到接口信息

### ISSUE THREAD

**Issue by buptlibo** [ZhangYuanSheng1217/RestfulTool#26]
```
Error executing task core.view.window.frame.RightToolWindow$$Lambda$3227/0x0000000801d9f840@276f80b1

java.lang.IllegalArgumentException: No enum constant core.beans.HttpMethod.OPTIONS
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at core.beans.HttpMethod.valueOf(HttpMethod.java:21)
	at core.utils.scanner.SpringHelper.getRequests(SpringHelper.java:142)
	at core.utils.scanner.SpringHelper.getRequests(SpringHelper.java:201)
	at core.utils.scanner.SpringHelper.getSpringRequestByModule(SpringHelper.java:56)
	at core.utils.RestUtil.getAllRequestByModule(RestUtil.java:188)
	at core.utils.RestUtil.getAllRequest(RestUtil.java:163)
	at core.utils.RestUtil.getAllRequest(RestUtil.java:147)
	at core.view.window.frame.RightToolWindow.getRequests(RightToolWindow.java:243)
	at core.view.window.frame.RightToolWindow.lambda$renderRequestTree$10(RightToolWindow.java:252)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:434)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:426)
	at com.intellij.openapi.project.DumbServiceImpl$TrackedEdtActivity.run(DumbServiceImpl.java:909)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

在idea中报了这个错误，怀疑是不是插件Enum文件中没有考虑到OPTIONS类型导致的问题

**Comment by ZhangYuanSheng1217** [comment]
这个确实没加OPTIONS请求
