### ISSUE TITLE
Adapt to IDEA 2021.1

### ISSUE THREAD

**Issue by ileeoyo** [ZhangYuanSheng1217/RestfulTool#65]
**Is your feature request related to a problem? Please describe.**
Adapt to IDEA 2021.1,I got an error in IDEA 2021.1 with the latest RestfulTool (1.2.9)
```
java.lang.NoClassDefFoundError: Could not initialize class com.github.restful.tool.beans.settings.Settings$IconTypeOptionForm
	at com.github.restful.tool.view.icon.Icons.getMethodIcon(Icons.java:44)
	at com.github.restful.tool.view.icon.Icons.getMethodIcon(Icons.java:40)
	at com.github.restful.tool.beans.Request.<init>(Request.java:33)
	at com.github.restful.tool.utils.scanner.SpringHelper.lambda$getRequests$3(SpringHelper.java:220)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.github.restful.tool.utils.scanner.SpringHelper.getRequests(SpringHelper.java:215)
	at com.github.restful.tool.utils.scanner.SpringHelper.getRequests(SpringHelper.java:66)
	at com.github.restful.tool.utils.scanner.SpringHelper.getSpringRequestByModule(SpringHelper.java:46)
	at com.github.restful.tool.utils.RequestUtil.getModuleRequests(RequestUtil.java:94)
	at com.github.restful.tool.utils.RequestUtil.getAllRequests(RequestUtil.java:58)
	at com.github.restful.tool.utils.RequestUtil.getAllRequests(RequestUtil.java:41)
	at com.github.restful.tool.view.window.frame.RightToolWindow.getRequests(RightToolWindow.java:92)
	at com.github.restful.tool.view.window.frame.RightToolWindow.lambda$refreshRequestTree$2(RightToolWindow.java:108)
	at com.intellij.openapi.project.DumbServiceImpl.doUnsafeRunWhenSmart(DumbServiceImpl.java:258)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$runWhenSmart$0(DumbServiceImpl.java:244)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runAfterOpened(StartupManagerImpl.java:503)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:244)
	at com.github.restful.tool.view.window.frame.RightToolWindow.refreshRequestTree(RightToolWindow.java:108)
	at com.github.restful.tool.actions.RefreshAction.actionPerformed(RefreshAction.java:38)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAware$5(ActionUtil.java:273)
	at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:273)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:201)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:174)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:157)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:470)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:836)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Describe the solution you'd like**
no

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by zhanggang807** [comment]
mark

**Comment by davichi11** [comment]
same error

**Comment by wangxuekai** [comment]
同求

**Comment by zhuxiang555111** [comment]
force update

**Comment by 2608027102** [comment]
gitee上面作者更新了beta版 https://gitee.com/zys981029/RestfulTool/releases/1.3.1

**Comment by RuoBingCoder** [comment]
同求

**Comment by ileeoyo** [comment]
solved
