### ISSUE TITLE
incompatible with idea 2021.2

### ISSUE THREAD

**Issue by ericshen90** [ZhangYuanSheng1217/RestfulTool#76]
Device：`MacMini(2018)`
OS：`BigSur 11.2.3`
IDEA：`IntelliJ IDEA 2021.2 (Ultimate Edition) Build #IU-212.4746.92, built on July 27, 2021`
ScreenShot:
![2021-07-28 104027](https://user-images.githubusercontent.com/18474225/127255067-0ccacf8a-419e-4bbd-9ca9-00b0d2e9b33b.png)

![2021-07-28 104036](https://user-images.githubusercontent.com/18474225/127255061-611e0655-efc4-4d73-8087-752f7413879f.png)

Log：
```
Worker exited due to exception

java.lang.NoClassDefFoundError: Could not initialize class com.github.restful.tool.beans.settings.Settings$IconTypeOptionForm
	at com.github.restful.tool.view.icon.Icons.getMethodIcon(Icons.java:44)
	at com.github.restful.tool.view.icon.Icons.getMethodIcon(Icons.java:40)
	at com.github.restful.tool.beans.Request.<init>(Request.java:33)
	at com.github.restful.tool.utils.scanner.SpringHelper.lambda$getRequests$3(SpringHelper.java:220)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.github.restful.tool.utils.scanner.SpringHelper.getRequests(SpringHelper.java:215)
	at com.github.restful.tool.utils.scanner.SpringHelper.getRequests(SpringHelper.java:66)
	at com.github.restful.tool.utils.scanner.SpringHelper.getSpringRequestByModule(SpringHelper.java:46)
	at com.github.restful.tool.utils.RequestUtil.getModuleRequests(RequestUtil.java:94)
	at com.github.restful.tool.utils.RequestUtil.getAllRequests(RequestUtil.java:58)
	at com.github.restful.tool.utils.RequestUtil.getAllRequests(RequestUtil.java:41)
	at com.github.restful.tool.view.search.GotoRequestContributor.getNames(GotoRequestContributor.java:48)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.processContributorNames(ContributorsBasedGotoByModel.java:134)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:85)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:79)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:854)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:11)
	at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$2(JobLauncherImpl.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$3(JobLauncherImpl.java:138)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:828)
	at com.intellij.concurrency.JobLauncherImpl.processImmediatelyIfTooFew(JobLauncherImpl.java:149)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:45)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:49)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.processNames(ContributorsBasedGotoByModel.java:101)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.getAllNames(DefaultChooseByNameItemProvider.java:187)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.getSortedNames(DefaultChooseByNameItemProvider.java:155)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.getSortedNamesForAllWildcards(DefaultChooseByNameItemProvider.java:130)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.filterElements(DefaultChooseByNameItemProvider.java:113)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.lambda$filterElementsWithWeights$3(DefaultChooseByNameItemProvider.java:75)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.filterElementsWithWeights(DefaultChooseByNameItemProvider.java:74)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.filterElements(DefaultChooseByNameItemProvider.java:48)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.addElementsByPattern(ChooseByNameBase.java:1424)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.fillWithScopeExpansion(ChooseByNameBase.java:1401)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.populateElements(ChooseByNameBase.java:1384)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.lambda$performInReadAction$1(ChooseByNameBase.java:1347)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.util.indexing.FileBasedIndexEx.ignoreDumbMode(FileBasedIndexEx.java:588)
	at com.intellij.util.indexing.DumbModeAccessType.ignoreDumbMode(DumbModeAccessType.java:55)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.performInReadAction(ChooseByNameBase.java:1347)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.lambda$r
```

**Comment by Klaus-Kin** [comment]
the same

**Comment by goecho** [comment]
java.lang.ExceptionInInitializerError
	at com.github.restful.tool.beans.settings.Settings$IconTypeOptionForm.<clinit>(Settings.java:170)
	at com.github.restful.tool.view.icon.Icons.getMethodIcon(Icons.java:44)
	at com.github.restful.tool.view.icon.Icons.getMethodIcon(Icons.java:40)
	at com.github.restful.tool.beans.Request.<init>(Request.java:33)
	at com.github.restful.tool.utils.scanner.SpringHelper.lambda$getRequests$3(SpringHelper.java:220)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.github.restful.tool.utils.scanner.SpringHelper.getRequests(SpringHelper.java:215)
	at com.github.restful.tool.utils.scanner.SpringHelper.getRequests(SpringHelper.java:66)
	at com.github.restful.tool.utils.scanner.SpringHelper.getSpringRequestByModule(SpringHelper.java:46)
	at com.github.restful.tool.utils.RequestUtil.getModuleRequests(RequestUtil.java:94)
	at com.github.restful.tool.utils.RequestUtil.getAllRequests(RequestUtil.java:58)
	at com.github.restful.tool.utils.RequestUtil.getAllRequests(RequestUtil.java:41)
	at com.github.restful.tool.view.window.frame.RightToolWindow.getRequests(RightToolWindow.java:92)
	at com.github.restful.tool.view.window.frame.RightToolWindow.lambda$refreshRequestTree$2(RightToolWindow.java:108)
	at com.intellij.openapi.project.DumbServiceImpl.doUnsafeRunWhenSmart(DumbServiceImpl.java:256)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$runWhenSmart$0(DumbServiceImpl.java:242)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runAfterOpened(StartupManagerImpl.kt:397)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:242)
	at com.github.restful.tool.view.window.frame.RightToolWindow.refreshRequestTree(RightToolWindow.java:108)
	at com.github.restful.tool.view.window.frame.RightToolWindow.firstLoad(RightToolWindow.java:87)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$smartInvokeLater$9(DumbServiceImpl.java:530)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:886)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:755)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:487)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NullPointerException
	at com.github.restful.tool.view.icon.IconTypeManager.autoScanner(IconTypeManager.java:105)
	at com.github.restful.tool.view.icon.IconTypeManager.<clinit>(IconTypeManager.java:39)
	... 50 more

**Comment by GitHuawei** [comment]
![9C7WHOY(_K GH2C(D~8UF(G](https://user-images.githubusercontent.com/42823616/127279554-ab2b612f-d798-4450-841f-a0d3355916fb.png)
上图中报空指针的错误行已标注，但该行代码已经被删除，具体是啥原因呢，是不是代码构建一次就OK了

**Comment by z744489075** [comment]
> 

2021.2 的版本被回退了 使用的版本是 1.2.8.219  并不是最新版本

**Comment by z744489075** [comment]
@GitHuawei

**Comment by Klaus-Kin** [comment]
@z744489075 那再等等?

**Comment by zcyc** [comment]
同样，新版本不能用了。
不过我发现，idea官方的功能可能已经覆盖了这个插件的功能。
大家可以看一下 endpoints。
![image](https://user-images.githubusercontent.com/9925064/127968111-6b3c62c9-95d2-4f65-b70a-e8c168ba3313.png)

**Comment by stormxiong** [comment]
坐等更新，挺好用的一个工具

**Comment by slankka** [comment]
2021.2 not work! 坐等更新！！

**Comment by tangyb828** [comment]
期待更新

**Comment by cy-default** [comment]
期待更新

**Comment by 2608027102** [comment]
> ![9C7WHOY(_K GH2C(D~8UF(G](https://user-images.githubusercontent.com/42823616/127279554-ab2b612f-d798-4450-841f-a0d3355916fb.png)
> 上图中报空指针的错误行已标注，但该行代码已经被删除，具体是啥原因呢，是不是代码构建一次就OK了

确实可以用

**Comment by chachae** [comment]
the same

**Comment by xuzexin-hz** [comment]
伤心，遇到同样的问题

**Comment by Leibnizhu** [comment]
一个可用的替代： https://plugins.jetbrains.com/plugin/16788-restfultoolkit-fix

**Comment by dutengfei789** [comment]
等更新的第四天

**Comment by mojitoming** [comment]
> 同样，新版本不能用了。
> 不过我发现，idea官方的功能可能已经覆盖了这个插件的功能。
> 大家可以看一下 endpoints。
> ![image](https://user-images.githubusercontent.com/9925064/127968111-6b3c62c9-95d2-4f65-b70a-e8c168ba3313.png)

### Endpoints 检索的速度有点慢啊，有木有好的优化方案～

**Comment by Klaus-Kin** [comment]
> > 同样，新版本不能用了。
> > 不过我发现，idea官方的功能可能已经覆盖了这个插件的功能。
> > 大家可以看一下 endpoints。
> > ![image](https://user-images.githubusercontent.com/9925064/127968111-6b3c62c9-95d2-4f65-b70a-e8c168ba3313.png)
> 
> ### Endpoints 检索的速度有点慢啊，有木有好的优化方案～

好像并不能映射出RequestBody中的实体参数,我果断退回前一版本

**Comment by ericshen90** [comment]
FYI：在RestfulTool作者修复好前，可以用[RestfulToolkit-fix](https://plugins.jetbrains.com/plugin/16788-restfultoolkit-fix)顶一下

**Comment by dutengfei789** [comment]
等更新的第五天

**Comment by githubwubicheng** [comment]
试试这个https://drive.google.com/file/d/1RnQxF6KSFDLENMHjGHfdnE1QtbwM0H6c/view?usp=sharing

**Comment by Yuonsa** [comment]
1.4.0已在审核中
