### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by gaoming95** [ZhangYuanSheng1217/RestfulTool#79]
java.lang.StackOverflowError
	at java.base/java.util.AbstractList.subList(AbstractList.java:497)
	at com.intellij.psi.stubs.StubList.getChildrenStubs(StubList.java:144)
	at com.intellij.psi.stubs.StubBase.getChildrenStubs(StubBase.java:39)
	at com.intellij.psi.stubs.StubBase.getChildrenByType(StubBase.java:94)
	at com.intellij.psi.impl.compiled.ClsModifierListImpl.getAnnotations(ClsModifierListImpl.java:61)
	at com.intellij.psi.impl.PsiImplUtil.findAnnotation(PsiImplUtil.java:288)
	at com.intellij.psi.impl.compiled.ClsModifierListImpl.findAnnotation(ClsModifierListImpl.java:71)
	at com.intellij.psi.PsiJvmConversionHelper.getListAnnotation(PsiJvmConversionHelper.java:53)
	at com.intellij.psi.PsiModifierListOwner.getAnnotation(PsiModifierListOwner.java:41)
	at com.intellij.psi.PsiJvmModifiersOwner.getAnnotation(PsiJvmModifiersOwner.java:27)
	at com.github.restful.tool.utils.RestUtil.getQualifiedAnnotation(RestUtil.java:258)
	at com.github.restful.tool.utils.RestUtil.getQualifiedAnnotation(RestUtil.java:263)

**Comment by jlfsdtc** [comment]
version 1.4.2 has this error too
![image](https://user-images.githubusercontent.com/29626183/131429486-42abe650-50ef-4bf6-a750-122a619050c0.png)

**Comment by jlfsdtc** [comment]
![image](https://user-images.githubusercontent.com/29626183/131429570-602b07f5-09b2-4829-8ab7-7b0d61e0dc09.png)
