### ISSUE TITLE
IDEA 2021.2.1(Ultimate Edition) 报错

### ISSUE THREAD

**Issue by zzqo** [ZhangYuanSheng1217/RestfulTool#83]
org.jetbrains.mvstore.MVStoreException: End of file /Applications/IntelliJ IDEA.app/Contents/bin/icons.db (position=7848425, length null, read=0, remaining=32768)
	at org.jetbrains.mvstore.DataUtil.readFully(DataUtil.java:110)
	at org.jetbrains.mvstore.FileStore.readFully(FileStore.java:124)
	at org.jetbrains.mvstore.Chunk.readBufferForPage(Chunk.java:436)
	at org.jetbrains.mvstore.MVStore.doReadPage(MVStore.java:2630)
	at org.jetbrains.mvstore.MVStore.lambda$readPage$9(MVStore.java:2616)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$13(BoundedLocalCache.java:2439)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1947)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2437)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2420)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:104)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
	at org.jetbrains.mvstore.MVStore.readPage(MVStore.java:2616)
	at org.jetbrains.mvstore.NonLeafPage.getChildPage(NonLeafPage.java:62)
	at org.jetbrains.mvstore.Page.get(Page.java:205)
	at org.jetbrains.mvstore.MVMap.get(MVMap.java:372)
	at com.intellij.ui.svg.SvgPrebuiltCacheManager.loadFromCache(SvgPrebuiltCacheManager.java:48)
	at com.intellij.util.SVGLoader.loadFromClassResource(SVGLoader.java:144)
	at com.intellij.ui.RasterizedImageDataLoader.loadRasterized(RasterizedImageDataLoader.java:138)
	at com.intellij.ui.RasterizedImageDataLoader.loadImage(RasterizedImageDataLoader.java:55)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.loadImage(IconLoader.java:962)
	at com.intellij.openapi.util.IconLoader$ScaledIconCache.getOrScaleIcon(IconLoader.java:1031)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.getRealIcon(IconLoader.java:850)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.getIconWidth(IconLoader.java:778)
	at com.intellij.openapi.actionSystem.impl.ActionButton.getPreferredSize(ActionButton.java:271)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.getChildPreferredSize(ActionToolbarImpl.java:490)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.getMaxButtonHeight(ActionToolbarImpl.java:512)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.calculateBoundsNowrapImpl(ActionToolbarImpl.java:549)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.calculateBounds(ActionToolbarImpl.java:822)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updatePreferredSize(ActionToolbarImpl.java:865)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.getPreferredSize(ActionToolbarImpl.java:860)
	at java.desktop/javax.swing.BoxLayout.checkRequests(BoxLayout.java:480)
	at java.desktop/javax.swing.BoxLayout.preferredLayoutSize(BoxLayout.java:297)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1823)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1807)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1685)
	at java.desktop/java.awt.BorderLayout.layoutContainer(BorderLayout.java:832)
	at java.desktop/java.awt.Container.layout(Container.java:1537)
	at java.desktop/java.awt.Container.doLayout(Container.java:1526)
	at java.desktop/java.awt.Container.validateTree(Container.java:1722)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validate(Container.java:1657)
	at java.desktop/java.awt.Container.validateUnconditionally(Container.java:1694)
	at java.desktop/java.awt.Window.pack(Window.java:836)
	at java.desktop/javax.swing.Popup$HeavyWeightWindow.show(Popup.java:262)
	at java.desktop/javax.swing.Popup.show(Popup.java:111)
	at com.intellij.ui.popup.PopupComponent$AwtPopupWrapper.show(PopupComponent.java:198)
	at com.intellij.ui.popup.AbstractPopup.show(AbstractPopup.java:1091)
	at com.intellij.ui.popup.AbstractPopup.show(AbstractPopup.java:810)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase.showTextFieldPanel(ChooseByNameBase.java:853)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase.initUI(ChooseByNameBase.java:655)
	at com.intellij.ide.util.gotoByName.ChooseByNamePopup.initUI(ChooseByNamePopup.java:87)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase.invoke(ChooseByNameBase.java:246)
	at com.intellij.ide.actions.GotoActionBase.showNavigationPopup(GotoActionBase.java:242)
	at com.github.restful.tool.view.search.GotoRequestAction.showNavigationPopup(GotoRequestAction.java:110)
	at com.github.restful.tool.view.search.GotoRequestAction.gotoActionPerformed(GotoRequestAction.java:88)
	at com.intellij.ide.actions.GotoActionBase.actionPerformed(GotoActionBase.java:57)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:65)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:563)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$8(IdeKeyEventDispatcher.java:677)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:261)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:670)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:603)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:574)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:457)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:450)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:218)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:800)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:494)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by newhoo** [comment]
试试RESTKit，同源，功能更强大，自用
https://github.com/newhoo/RESTKit
