### ISSUE TITLE
IntelliJ IDEA 2021.3 (Ultimate Edition)无法正常使用

### ISSUE THREAD

**Issue by zzqo** [ZhangYuanSheng1217/RestfulTool#86]
Worker exited due to exception

java.lang.NoClassDefFoundError: Could not initialize class com.github.restful.tool.beans.settings.Settings$IconTypeOptionForm
	at com.github.restful.tool.view.icon.Icons.getMethodIcon(Icons.java:44)
	at com.github.restful.tool.view.icon.Icons.getMethodIcon(Icons.java:40)
	at com.github.restful.tool.beans.Request.<init>(Request.java:33)
	at com.github.restful.tool.utils.scanner.SpringHelper.lambda$getRequests$3(SpringHelper.java:220)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.github.restful.tool.utils.scanner.SpringHelper.getRequests(SpringHelper.java:215)
	at com.github.restful.tool.utils.scanner.SpringHelper.getRequests(SpringHelper.java:66)
	at com.github.restful.tool.utils.scanner.SpringHelper.getSpringRequestByModule(SpringHelper.java:46)
	at com.github.restful.tool.utils.RequestUtil.getModuleRequests(RequestUtil.java:94)
	at com.github.restful.tool.utils.RequestUtil.getAllRequests(RequestUtil.java:58)
	at com.github.restful.tool.utils.RequestUtil.getAllRequests(RequestUtil.java:41)
	at com.github.restful.tool.view.search.GotoRequestContributor.getNames(GotoRequestContributor.java:48)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.processContributorNames(ContributorsBasedGotoByModel.java:135)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:86)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:80)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:865)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:11)
	at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$2(JobLauncherImpl.java:140)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$3(JobLauncherImpl.java:136)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:839)
	at com.intellij.concurrency.JobLauncherImpl.processImmediatelyIfTooFew(JobLauncherImpl.java:147)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:47)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:49)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.processNames(ContributorsBasedGotoByModel.java:102)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.getAllNames(DefaultChooseByNameItemProvider.java:187)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.getSortedNames(DefaultChooseByNameItemProvider.java:155)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.getSortedNamesForAllWildcards(DefaultChooseByNameItemProvider.java:130)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.filterElements(DefaultChooseByNameItemProvider.java:113)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.lambda$filterElementsWithWeights$3(DefaultChooseByNameItemProvider.java:75)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.filterElementsWithWeights(DefaultChooseByNameItemProvider.java:74)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.filterElements(DefaultChooseByNameItemProvider.java:48)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.addElementsByPattern(ChooseByNameBase.java:1424)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.fillWithScopeExpansion(ChooseByNameBase.java:1401)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.populateElements(ChooseByNameBase.java:1384)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.lambda$performInReadAction$1(ChooseByNameBase.java:1347)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.util.indexing.FileBasedIndexEx.ignoreDumbMode(FileBasedIndexEx.java:581)
	at com.intellij.util.indexing.DumbModeAccessType.ignoreDumbMode(DumbModeAccessType.java:55)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.performInReadAction(ChooseByNameBase.java:1347)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.lambda$runBackgroundProcess$0(ChooseByNameBase.java:1335)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$0(DumbService.java:113)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:865)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:150)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:113)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.runBackgroundProcess(ChooseByNameBase.java:1335)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$5(ProgressIndicatorUtils.java:265)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:263)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:213)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by hpfs0** [comment]
我也是同样问题

**Comment by Skylab-git** [comment]
求解决踢我一下
Worker exited due to exception

java.lang.ExceptionInInitializerError
	at com.github.restful.tool.beans.settings.Settings$IconTypeOptionForm.<clinit>(Settings.java:170)
	at com.github.restful.tool.view.icon.Icons.getMethodIcon(Icons.java:44)
	at com.github.restful.tool.view.icon.Icons.getMethodIcon(Icons.java:40)
	at com.github.restful.tool.beans.Request.<init>(Request.java:33)
	at com.github.restful.tool.utils.scanner.SpringHelper.lambda$getRequests$3(SpringHelper.java:220)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.github.restful.tool.utils.scanner.SpringHelper.getRequests(SpringHelper.java:215)
	at com.github.restful.tool.utils.scanner.SpringHelper.getRequests(SpringHelper.java:66)
	at com.github.restful.tool.utils.scanner.SpringHelper.getSpringRequestByModule(SpringHelper.java:46)
	at com.github.restful.tool.utils.RequestUtil.getModuleRequests(RequestUtil.java:94)
	at com.github.restful.tool.utils.RequestUtil.getAllRequests(RequestUtil.java:58)
	at com.github.restful.tool.utils.RequestUtil.getAllRequests(RequestUtil.java:41)
	at com.github.restful.tool.view.search.GotoRequestContributor.getNames(GotoRequestContributor.java:48)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.processContributorNames(ContributorsBasedGotoByModel.java:135)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:86)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel$1.processInReadAction(ContributorsBasedGotoByModel.java:80)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:865)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:11)
	at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$2(JobLauncherImpl.java:140)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$3(JobLauncherImpl.java:136)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:839)
	at com.intellij.concurrency.JobLauncherImpl.processImmediatelyIfTooFew(JobLauncherImpl.java:147)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:47)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:49)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.processNames(ContributorsBasedGotoByModel.java:102)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.getAllNames(DefaultChooseByNameItemProvider.java:187)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.getSortedNames(DefaultChooseByNameItemProvider.java:155)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.getSortedNamesForAllWildcards(DefaultChooseByNameItemProvider.java:130)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.filterElements(DefaultChooseByNameItemProvider.java:113)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.lambda$filterElementsWithWeights$3(DefaultChooseByNameItemProvider.java:75)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.filterElementsWithWeights(DefaultChooseByNameItemProvider.java:74)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.filterElements(DefaultChooseByNameItemProvider.java:48)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.addElementsByPattern(ChooseByNameBase.java:1424)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.fillWithScopeExpansion(ChooseByNameBase.java:1401)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.populateElements(ChooseByNameBase.java:1384)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.lambda$performInReadAction$1(ChooseByNameBase.java:1347)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.util.indexing.FileBasedIndexEx.ignoreDumbMode(FileBasedIndexEx.java:581)
	at com.intellij.util.indexing.DumbModeAccessType.ignoreDumbMode(DumbModeAccessType.java:55)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.performInReadAction(ChooseByNameBase.java:1347)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.lambda$runBackgroundProcess$0(ChooseByNameBase.java:1335)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$0(DumbService.java:113)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:865)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:150)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:113)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.runBackgroundProcess(ChooseByNameBase.java:1335)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$5(ProgressIndicatorUtils.java:265)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:263)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:213)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
	at com.github.restful.tool.view.icon.IconTypeManager.autoScanner(IconTypeManager.java:105)
	at com.github.restful.tool.view.icon.IconTypeManager.<clinit>(IconTypeManager.java:39)
	... 75 more

**Comment by WangslVIP** [comment]
I have the same problem

**Comment by lipengfei5266** [comment]
我也是
java.lang.NoClassDefFoundError: Could not initialize class com.github.restful.tool.beans.settings.Settings$IconTypeOptionForm
	at com.github.restful.tool.view.icon.Icons.getMethodIcon(Icons.java:44)
	at com.github.restful.tool.view.icon.Icons.getMethodIcon(Icons.java:40)
	at com.github.restful.tool.beans.Request.<init>(Request.java:33)
	at com.github.restful.tool.utils.scanner.SpringHelper.lambda$getRequests$3(SpringHelper.java:220)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.github.restful.tool.utils.scanner.SpringHelper.getRequests(SpringHelper.java:215)
	at com.github.restful.tool.utils.scanner.SpringHelper.getRequests(SpringHelper.java:240)
	at com.github.restful.tool.utils.scanner.SpringHelper.getRequests(SpringHelper.java:71)
	at com.github.restful.tool.utils.scanner.SpringHelper.getSpringRequestByModule(SpringHelper.java:46)
	at com.github.restful.tool.utils.RequestUtil.getModuleRequests(RequestUtil.java:94)
	at com.github.restful.tool.utils.RequestUtil.getAllRequests(RequestUtil.java:58)
	at com.github.restful.tool.utils.RequestUtil.getAllRequests(RequestUtil.java:41)
	at com.github.restful.tool.view.window.frame.RightToolWindow.getRequests(RightToolWindow.java:92)
	at com.github.restful.tool.view.window.frame.RightToolWindow.lambda$refreshRequestTree$2(RightToolWindow.java:108)
	at com.intellij.openapi.project.DumbServiceImpl.doUnsafeRunWhenSmart(DumbServiceImpl.java:259)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$runWhenSmart$0(DumbServiceImpl.java:243)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runAfterOpened(StartupManagerImpl.kt:438)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:243)
	at com.github.restful.tool.view.window.frame.RightToolWindow.refreshRequestTree(RightToolWindow.java:108)
	at com.github.restful.tool.view.window.frame.RightToolWindow.firstLoad(RightToolWindow.java:87)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$smartInvokeLater$9(DumbServiceImpl.java:530)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by Klaus-Kin** [comment]
+1

**Comment by davichi11** [comment]
作者是不是不更新了啊

**Comment by WangslVIP** [comment]
暂时可以用替代方案，IDEA自带的快捷键搜索，直接搜接口，ctrl + shift + \

**Comment by slankka** [comment]
Community 2021.3 也无法使用。没有Ctrl + shift + \

**Comment by LuckyMango** [comment]
这么好的项目作者都不维护了么

**Comment by ge00111** [comment]
**这么好用的工具,作者不管了么?**

**Comment by Skylab-git** [comment]
> 暂时可以用替代方案，IDEA自带的快捷键搜索，直接搜接口，ctrl + shift + \

按了这个快捷键没反应呀

**Comment by suwia** [comment]
mac 可以 使用 command + shift + \

**Comment by xiaosheng0** [comment]
`Ctrl + shift + \`效果出来是这样的,挺好用
![image](https://user-images.githubusercontent.com/31728580/145504327-d161baed-efa7-4ade-a104-e0871bd0b2e9.png)
快捷键按需自定义
![image](https://user-images.githubusercontent.com/31728580/145505054-e256d33c-f5c6-4cb1-929d-2fa9ac88db83.png)

**Comment by Skylab-git** [comment]
> `Ctrl + shift + \`效果出来是这样的,挺好用 ![image](https://user-images.githubusercontent.com/31728580/145504327-d161baed-efa7-4ade-a104-e0871bd0b2e9.png) 快捷键按需自定义 ![image](https://user-images.githubusercontent.com/31728580/145505054-e256d33c-f5c6-4cb1-929d-2fa9ac88db83.png)

 兄弟们 这个方案可行 我试了

**Comment by lifepassion** [comment]
I have the same problem

**Comment by kevin-onepiece** [comment]
我升级到最新版本，1.4.5 就解决了

**Comment by kevin-onepiece** [comment]
@Skylab-git 快来

**Comment by kevin-onepiece** [comment]
@zzqo @hpfs0 @davichi11 @slankka @ge00111 @lipengfei5266 @WangslVIP @davichi11 restfultool 可以使用了

**Comment by newhoo** [comment]
> @zzqo @hpfs0 @davichi11 @slankka @ge00111 @lipengfei5266 @WangslVIP @davichi11 restfultool 可以使用了

自荐一下RESTKit，功能更强大，自用，长期维护
https://github.com/newhoo/RESTKit

**Comment by newhoo** [comment]
> > `Ctrl + shift + \`效果出来是这样的,挺好用 ![image](https://user-images.githubusercontent.com/31728580/145504327-d161baed-efa7-4ade-a104-e0871bd0b2e9.png) 快捷键按需自定义 ![image](https://user-images.githubusercontent.com/31728580/145505054-e256d33c-f5c6-4cb1-929d-2fa9ac88db83.png)
> 
> 兄弟们 这个方案可行 我试了

这个看起来是旗舰版自带的
